/*
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
    I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, I Hate C#, 
*/

using UnityEngine;

public class GunPickup : MonoBehaviour
{
    [Header("Gun Settings")]
    public GameObject gunPrefab;
    public GameObject bulletPrefab;
    
    [Header("Pickup Settings")]
    public float pickupRange = 2f;
    public bool useCollisionDetection = true;
    public bool useTriggerDetection = true;
    
    [Header("Visual Feedback")]
    public bool rotateGun = true;
    public float rotationSpeed = 50f;
    
    private void Start()
    {
        if (!TryGetComponent<Collider>(out var col))
        {
            col = gameObject.AddComponent<SphereCollider>();
            col.isTrigger = useTriggerDetection;
        }
        
        if (col is SphereCollider sphereCol)
        {
            sphereCol.radius = pickupRange;
            sphereCol.center = new Vector3(-.07f, .0f, .09f);
        }
    }
    
    private void Update()
    {
        if (rotateGun)
        {
            transform.Rotate(0, rotationSpeed * Time.deltaTime, 0);
        }
    }
    
    private void OnTriggerEnter(Collider other)
    {
        if (useTriggerDetection && other.CompareTag("Player"))
        {
            TryPickupGun(other.gameObject);
        }
    }
    
    private void OnCollisionEnter(Collision collision)
    {
        if (useCollisionDetection && collision.collider.CompareTag("Player"))
        {
            TryPickupGun(collision.collider.gameObject);
        }
    }
    
    private void TryPickupGun(GameObject player)
    {
        Transform gunHand = FindInChildren(player.transform, "GunPos");
        if (gunHand == null)
            gunHand = FindInChildren(player.transform, "GunHand");
            
        Transform gunPoint = FindInChildren(player.transform, "GunPoint");
        
        if (gunHand == null)
        {
            Debug.LogWarning("Player doesn't have a GunHand!");
            return;
        }
        
        if (gunHand.childCount > 0)
        {
            Debug.Log("Player already has a gun!");
            return;
        }
        
        if (gunPrefab != null)
        {
            Quaternion gunRotation = Quaternion.Euler(0, 0, 0);
            GameObject newGun = Instantiate(gunPrefab, Vector3.zero, gunRotation);
            newGun.transform.SetParent(gunHand, false);
            newGun.transform.localPosition = Vector3.zero;
            newGun.transform.localRotation = gunRotation;
            
            if (!newGun.TryGetComponent<GunHand>(out var gunComponent))
            {
                gunComponent = newGun.AddComponent<GunHand>();
            }
            
            if (gunPoint != null)
            {
                gunComponent.gunPoint = gunPoint;
            }
            
            if (bulletPrefab != null)
            {
                gunComponent.bulletPrefab = bulletPrefab;
            }
            
            Debug.Log("Gun picked up successfully!");
            
            Destroy(gameObject);
        }
    }
    
    private Transform FindInChildren(Transform parent, string name)
    {
        if (parent.name == name)
            return parent;
            
        foreach (Transform child in parent)
        {
            Transform found = FindInChildren(child, name);
            if (found != null)
                return found;
        }
        
        return null;
    }
}